# Generated by Django 5.2.18 on 2026-10-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Pending', max_length=50)),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('department', models.CharField(default='Pending', max_length=50)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
